title: "Sridevi Blogs"
email: ""
description: >-
  A DevOps blog focused on real-world learning and career growth — by Sridevi Velpula.
baseurl: ""
url: "https://srideviblogs.github.io"
twitter_username: ""
github_username: srideviblogs

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"  # Options: default, dark, contrast, sunrise, etc.

# Author
author:
  name: "Sridevi Velpula"
  # avatar: "/assets/images/profile.jpg"
  bio: "DevOps Engineer&nbsp;|&nbsp;Cloud Enthusiast&nbsp;|&nbsp;Lifelong Learner"
  location: "USA"

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Blog"
    url: /blog/
  - title: "About"
    url: /about/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

# Custom CSS
defaults:
  - scope:
      path: ""
    values:
      css: "assets/css/custom.css"
      
# Ensure these are not removing your file
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

