title: "Welcome to Sridevi’s DevOps Blog"
description: "Hi there! 👋 I’m Sridevi, and this is my space to share insights, stories, and tutorials from my journey in DevOps, SRE, Kubernetes, CI/CD, and beyond.
  Whether you’re just getting started or looking for advanced tips, I hope you’ll find something useful and inspiring here.
  Stay tuned — more content coming soon!."
url: "https://srideviblogs.github.io"
baseurl: ""  # Keep this blank for user site (not a project page)

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Author info
author:
  name: "Sridevi Velpula"
  avatar: "/assets/images/avatar.png"  # Optional: Add your photo to assets/images/
  bio: "DevOps Engineer | Blogger | Lifelong Learner"
  location: "USA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/srideviblogs"

# Theme design
minimal_mistakes_skin: "air"  # Options: default, dark, air, neon, etc.
locale: "en-US"
logo: "/assets/images/logo.png"  # Optional: place logo image in assets/images/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:categories/:title/

# Navigation bar
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Blog Posts"
    url: /year-archive/
  - title: "Contact"
    url: /contact/

# Pagination
paginate: 5
paginate_path: /page:num/
