title: "Sridevi Blogs"
description: "A DevOps blog focused on real-world learning and career growth — by Sridevi Velpula."
baseurl: "" 
url: "https://srideviblogs.github.io"
theme: millennial

author:
  name: "Sridevi Velpula"
  github: srideviblogs
  linkedin: "https://www.linkedin.com/in/sandeep-pochu-27589b274/"
  location: "Santa Clara, CA"
  bio: "DevOps Engineer | Blogger | Tech Enthusiast"

permalink: /:title/
paginate: 5
paginate_path: "/page:num/"

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blogs
    url: /blogs/

google_analytics: ""  # Optional
disqus: ""            # Optional
